Configs compilation and jinja templates, renaming
rvadim/elastalert-k8s-automation pull request #15
Opened 2019-04-23 06:31 UTC by Kuyantsev-VP

2019-04-23 07:39 UTC, rvadim requested changes

2019-04-23 07:39 UTC, rvadim commented on Dockerfile
> +ADD ./schemas/admin_validation_schema.yaml ./schemas/
```
ADD schemas ./schemas
```

2019-04-23 07:39 UTC, rvadim commented on config_compile.py
> +    env = Environment(loader=FileSystemLoader('jinja_templates'),
Just 'templates'

2019-04-23 07:39 UTC, rvadim commented on config_compile.py
> +                      trim_blocks=True,
Leave this variable defaulted please

2019-04-23 07:50 UTC, Kuyantsev-VP commented on config_compile.py
> +                      trim_blocks=True,
done

2019-04-23 07:50 UTC, Kuyantsev-VP commented on config_compile.py
> +    env = Environment(loader=FileSystemLoader('jinja_templates'),
done

2019-04-23 07:50 UTC, Kuyantsev-VP commented on Dockerfile
> +ADD ./schemas/admin_validation_schema.yaml ./schemas/
done

2019-04-24 01:35 UTC, rvadim approved these changes

2019-04-24 01:36 UTC, merged