Documentation
rvadim/elastalert-k8s-automation pull request #28
Opened 2019-05-08 09:47 UTC by Kuyantsev-VP

PR to demonstrate current progress in working on documentation

2019-05-08 10:09 UTC, rvadim requested changes

2019-05-08 10:09 UTC, rvadim commented on README.md
> +* Local mode allows to run application without deployment in Kubernetes.
... For testing purposes.

2019-05-08 10:09 UTC, rvadim commented on README.md
> +Clone elastlert-k8s-automation project:
Actually for installation we need to just `kubectl apply -f <URL to file with deployment and config>`.
So, in this case we need to prepare docker image building and merge deployment and configmap to one file in `example` directory.
I will prepare docker image building, and you should create example.

2019-05-08 10:09 UTC, rvadim commented on README.md
> +rules_folder: # Directory with ElastAlert rules
This options not required, due to it calculated. Also, changing this parameter may cause fail to start.

2019-05-08 10:09 UTC, rvadim commented on README.md
> +Example of administrator configuration file can be found in
Link is better.

2019-05-08 10:09 UTC, rvadim commented on README.md
> +Example of general alert settings in the admin config can be found in
Link

2019-05-08 10:09 UTC, rvadim commented on README.md
> +Example of general alert settings in the admin config can be found in
But inserting example inline here is better then link for this.

2019-05-08 10:09 UTC, rvadim commented on README.md
> +/tests/fixtures/renderer_test_user_rules.yaml
Insert example inline

2019-05-14 13:07 UTC, rvadim requested changes

2019-05-14 13:07 UTC, rvadim commented on README.md
> +$ kubectl apply -f <URL to file with deployment and config>
https://github.com/rvadim/elastalert-k8s-automation/blob/master/deploy/deploy.yaml

2019-05-14 13:07 UTC, rvadim commented on README.md
> +$ kubectl apply -f <URL to file with deployment and config>
But need to merge configmap to deploy.yaml

2019-05-15 07:34 UTC, rvadim approved these changes
LGTM

2019-05-15 07:34 UTC, dkondyrev commented on README.md
> +$ kubectl apply -f <URL to file with deployment and config>
Changed

2019-05-15 07:35 UTC, dkondyrev approved these changes

2019-05-15 07:36 UTC, merged